### ISSUE TITLE
Alerts does not work on SFOS 4.4.0.58 (Gemini PDA)

### ISSUE THREAD

**Issue by okruhliak** [a-dekker/cooktimer#6]
Nothing happens at the end of the set time.  On 4.3.0.15 (Xperia X) this works fine.

**Comment by a-dekker** [comment]
I'm on SFOS 4.4.0.58 using an Xperia XA2 Plus, and I experiencing no issues. So I do not think it is SFOS 4.4 related.

Do regular alarms work, and do you have any console logging which might give a hint?

**Comment by a-dekker** [comment]
And you are using Cooktimer version 0.4.1? That's the one that should opt out of sailjail.

**Comment by okruhliak** [comment]
I uninstalled Coocktimer (it didn't show me any version, only "Version" without a label) and reinstalled from Storeman version 0.4-1, everything works.
It is possible that I have had this bug since SFOS 4.3.xx, but I did not test it, I use Gemini for other things, sorry.
Working in landscape mode is a bit awkward, but otherwise it's okay, thanks. :)

**Comment by a-dekker** [comment]
The fact that it didn't show a version indicates you where using an old version. The old cooktimer app found its version by using the external rpm command, which is no longer allowed because of sailjail. Calling the external alarm is also no longer possible with sailjail, so that explains your issue.

I can image the landscape mode does not look too good. I had a lot of trouble making it look okay on the devices I have, and the Gemini probably has other dimensions.
